@startuml

interface IDatabase {
    + getData(): []
}

class Database {
    + getData(): []
}

class ProxyDatabase {
    + getData(): []
}

IDatabase <.. Database
IDatabase <.. ProxyDatabase

ProxyDatabase o--> Database

@enduml
