@startuml

interface ActiveRecord {
    + save(): void
    + delete(): void
}

class PersonActiveRecord {
    + id: int
    + firstName: string
    + lastName: string
    + email: string
    + {static} find(id): PersonActiveRecord | null
    + {static} findAll(): PersonActiveRecord[]
}

ActiveRecord <|.. PersonActiveRecord

@enduml
