@startuml
interface IModel {
    + id: int
}

class UnitOfWork {
    + registerCreated(model): void
    + registerUpdated(model): void
    + registerRemoved(model): void
    + commit(): void
}

UnitOfWork .> IModel

@enduml
