@startuml

enum Currency {
    USD
    EUR
}

class Money {
    - amount: int
    - currency: Currency

    + constructor (amount, currency)

    + getAmount(): int
    + getCurrency(): Currency

    + isEqual (money): boolean
    + isLess (money): boolean
    + isGreater (money): boolean

    + add (money): Money
    + subtract (money): Money
    + multiply (factor): Money
    + divide (factor): Money

    - assertSameCurrency (money): void
}

Money *-right-> Currency

@enduml
