@startuml
!startsub BaseStorage

class Record  {
    + id: int
    + text: string
}

class Storage {
    + read (id: int): Record
    + write (record: Record): void
    + clear(): void
}

Storage ..> Record
!endsub
@enduml
