@startuml

class PersonFinder {
    + findAll (): PersonRowGateway[]
    + find (id): PersonRowGateway | null
}

class PersonRowGateway {
    + id: int
    + firstName: string
    + lastName: string
    + email: string
    + create (): void
    + update (): void
    + delete (): void
}

class Person {
    - PersonRowGateway
    + getId(): int
    + getFirstName(): string
    + getLastName(): string
    + getEmail(): string
}

Person o-->PersonRowGateway
PersonFinder .right.> PersonRowGateway

@enduml
