### Add
POST http://www.dneonline.com/calculator.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: http://tempuri.org/Add

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Add xmlns="http://tempuri.org/">
            <intA>10</intA>
            <intB>5</intB>
        </Add>
    </soap:Body>
</soap:Envelope>

### Response
#<?xml version="1.0" encoding="utf-8"?>
#<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
#    <soap:Body>
#        <AddResponse xmlns="http://tempuri.org/">
#            <AddResult>15</AddResult>
#        </AddResponse>
#    </soap:Body>
#</soap:Envelope>

### Subtract
POST http://www.dneonline.com/calculator.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: http://tempuri.org/Subtract

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Subtract xmlns="http://tempuri.org/">
            <intA>10</intA>
            <intB>5</intB>
        </Subtract>
    </soap:Body>
</soap:Envelope>

### Response
# <?xml version="1.0" encoding="utf-8"?>
# <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
# <soap:Body>
#     <SubtractResponse xmlns="http://tempuri.org/">
#         <SubtractResult>5</SubtractResult>
#     </SubtractResponse>
# </soap:Body>
# </soap:Envelope>


### Multiply
POST http://www.dneonline.com/calculator.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: http://tempuri.org/Multiply

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Multiply xmlns="http://tempuri.org/">
            <intA>10</intA>
            <intB>5</intB>
        </Multiply>
    </soap:Body>
</soap:Envelope>

### Response
# <?xml version="1.0" encoding="utf-8"?>
# <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
#     <soap:Body>
#         <MultiplyResponse xmlns="http://tempuri.org/">
#             <MultiplyResult>50</MultiplyResult>
#         </MultiplyResponse>
#     </soap:Body>
# </soap:Envelope>

### Divide
POST http://www.dneonline.com/calculator.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: http://tempuri.org/Divide

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <Divide xmlns="http://tempuri.org/">
            <intA>10</intA>
            <intB>5</intB>
        </Divide>
    </soap:Body>
</soap:Envelope>

### Resonse
# <?xml version="1.0" encoding="utf-8"?>
# <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
#     <soap:Body>
#         <DivideResponse xmlns="http://tempuri.org/">
#             <DivideResult>2</DivideResult>
#         </DivideResponse>
#     </soap:Body>
# </soap:Envelope>
